federicoiosue/Omni-Notes

omniNotes/src/main/java/it/feio/android/omninotes/ListFragment.java

Probably it can be improved but it now works.
a. In trashNotes(), archiveNotes() and categorizeNotesExecute() each loop duplicated items
b. Put into undoNotesList absolute position
c. In onUndo insert items from the index lower

Fixed multi swipe and undo

---

omniNotes/src/main/java/it/feio/android/omninotes/BaseActivity.java
omniNotes/src/main/java/it/feio/android/omninotes/SettingsFragment.java
omniNotes/src/main/java/it/feio/android/omninotes/utils/Constants.java
omniNotes/src/main/java/it/feio/android/omninotes/utils/date/ReminderPickers.java
omniNotes/src/main/res/values/arrays.xml
omniNotes/src/main/res/values/strings.xml
omniNotes/src/main/res/xml/settings_interface.xml

Works fine, but accessing shared preferences in ReminderPickers could be improved.

Add setting to change first day of week in reminder calendar

---

build.gradle
gradle.properties
omniNotes/build.gradle
omniNotes/src/main/java/it/feio/android/omninotes/DetailFragment.java
omniNotes/src/main/java/it/feio/android/omninotes/ListFragment.java
omniNotes/src/main/java/it/feio/android/omninotes/models/adapters/NoteAdapter.java
omniNotes/src/main/java/it/feio/android/omninotes/models/holders/EmptyHolder.java
omniNotes/src/main/java/it/feio/android/omninotes/models/holders/NoteViewHolder.java
omniNotes/src/main/java/it/feio/android/omninotes/models/listeners/AbsListViewScrollDetector.java
omniNotes/src/main/java/it/feio/android/omninotes/models/manager/ExStaggeredGridLayoutManager.java
omniNotes/src/main/java/it/feio/android/omninotes/models/misc/HeaderSpanSizeLookup.java
omniNotes/src/main/java/it/feio/android/omninotes/models/misc/ItemClickSupport.java
omniNotes/src/main/java/it/feio/android/omninotes/models/views/ExRecyclerView.java
omniNotes/src/main/java/it/feio/android/omninotes/models/views/Fab.java
omniNotes/src/main/java/it/feio/android/omninotes/models/views/NoteDecoration.java
omniNotes/src/main/java/it/feio/android/omninotes/utils/Constants.java
omniNotes/src/main/res/layout/fragment_list.xml
omniNotes/src/main/res/layout/note_layout_grid.xml
omniNotes/src/main/res/menu/menu_list.xml
omniNotes/src/main/res/values-de-rDE/strings.xml
omniNotes/src/main/res/values/dimens.xml
omniNotes/src/main/res/values/ids.xml
omniNotes/src/main/res/values/strings.xml

This patch replaces the "DynamicListView" to list all notes with a "RecyclerView". It also adds a new view mode - staggered grid view (see attached screenshot).
I like the layout of Google Keep, so I tried to change this wonderful note taking app to better fit my tasting. This is especially useful on larger screen, like tablets.
It's not a simple change and the code is not perfect yet. Therefore, I understand if you choose to not merge this into the main application. But maybe someone will find this useful.
- translation
- testing

Use RecyclerView to display notes list and add new staggered grid layout

---

README.md

Mainly changed the second sentence so that it is easier to understand.

Some language fixes.

---

omniNotes/src/main/java/it/feio/android/omninotes/SettingsFragment.java

Оn my smartphone (Android 4.4.4) did not work three switches on the settings fragment . Everything is fine after these changes.

fixed incorrect behavior SwitchPreferences on SettingsFragment

---

omniNotes/src/main/java/it/feio/android/omninotes/DetailFragment.java
omniNotes/src/main/java/it/feio/android/omninotes/utils/Display.java

I'm testing this on android studio emulator API 23 everything ok.

Fixed: Note metadata hidden behind Android navigation #365

---

omniNotes/src/main/java/it/feio/android/omninotes/ListFragment.java
omniNotes/src/main/java/it/feio/android/omninotes/models/views/SketchView.java

I looked at oldest issues.While I worked on it I was finding another issue. When try edit  exist sketch, in context menu in the caption appear "null" and size in KB.

Fixes #13: Sketch stroke opacity is significantly darker

---

omniNotes/src/main/java/it/feio/android/omninotes/ListFragment.java
omniNotes/src/main/java/it/feio/android/omninotes/models/views/SketchView.java

Hello. I think the keyboard isn't shown because in DetailFragment.java on line 512 i.setAction(null). On  the "Null" Intent action property  build  part of logic of detailfragment and i didn't try to refactor it. Maybe exist another way to fix it, but this small fix works good.

Fix #311: Keyboard shown on new note only first time

---

omniNotes/src/main/java/it/feio/android/omninotes/DetailFragment.java
omniNotes/src/main/java/it/feio/android/omninotes/ListFragment.java

Bug Fix for Note Reminder Triggering After Being Removed

---

omniNotes/src/main/java/it/feio/android/omninotes/MainActivity.java

Bug fix for #439. After entering the correct password, the app now does not ask you again for your password once the screen orientation changes.

Bug Fix: App asks for password after changing screen orientation.

---

omniNotes/src/main/AndroidManifest.xml
omniNotes/src/main/java/it/feio/android/omninotes/DetailFragment.java
omniNotes/src/main/res/values/strings.xml

I recently try to attach a file but it can't be done, ANR happened. when tested in debug version contains error message because permission is rejected. Now the bug is fixed.

Read external storage permission on file attachment

---

omniNotes/src/main/java/it/feio/android/omninotes/ListFragment.java
omniNotes/src/main/java/it/feio/android/omninotes/MainActivity.java
omniNotes/src/main/java/it/feio/android/omninotes/async/UpdateWidgetsTask.java

If I get you right.If I get you right. This is new solution with using an asynctask which is waiting NotesUpdatedEvent . 
I didn't find how update previous pull request therefore created new one.

fixed #371 #339 widget shows deleted and archived note (async)

---

omniNotes/src/main/java/it/feio/android/omninotes/DetailFragment.java
omniNotes/src/main/res/drawable/ic_access_time_black_24px.xml
omniNotes/src/main/res/layout/attachment_dialog.xml
omniNotes/src/main/res/values/strings.xml

Hi! Maybe it is suitable implementation  for closed issue #319 #435

Feature: Add timestamp

---

omniNotes/src/main/java/it/feio/android/omninotes/helpers/date/DateHelper.java

A small, but useful change.  For issue  #448

Add day of the week on the remainder set label

---

omniNotes/src/main/java/it/feio/android/omninotes/CategoryActivity.java
omniNotes/src/main/java/it/feio/android/omninotes/DetailFragment.java
omniNotes/src/main/java/it/feio/android/omninotes/ListFragment.java
omniNotes/src/main/java/it/feio/android/omninotes/PasswordActivity.java
omniNotes/src/main/java/it/feio/android/omninotes/SettingsActivity.java
omniNotes/src/main/java/it/feio/android/omninotes/SettingsFragment.java
omniNotes/src/main/java/it/feio/android/omninotes/SketchFragment.java
omniNotes/src/main/java/it/feio/android/omninotes/async/UpdaterTask.java

DetailsFragment Leaked #654

---

fastlane/metadata/android/en-US/full_description.txt

Ref: https://gitlab.com/fdroid/fdroid-website/-/issues/498
Ref: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7251
Ref: https://f-droid.org/en/docs/Build_Metadata_Reference/#AntiFeatures

Add F-Droid AF description

---

omniNotes/src/androidTest/java/it/feio/android/omninotes/ui/SettingsActivityTest.java
omniNotes/src/androidTest/java/it/feio/android/omninotes/utils/ClickWithoutDisplayConstraint.java
omniNotes/src/androidTest/java/it/feio/android/omninotes/utils/IsEqualTrimmingAndIgnoringCase.java
omniNotes/src/androidTest/java/it/feio/android/omninotes/utils/VisibleViewMatcher.java

This PR adds an Espresso test case for the Settings Activity. It also includes three auxiliary classes with two custom Matchers and one custom ViewAction.
The test case was automatically generated using the [ETG](https://github.com/FlyingPumba/etg) tool, which aims to achieve high activity coverage. In particular, this Espresso test increases the current overall coverage in the project by 2.70%.
Although this contribution was automatically generated, the code in this PR was manually reviewed to adhere to the project's contributing guidelines.

Add test case for Settings Activity

---

omniNotes/src/androidTest/java/it/feio/android/omninotes/ui/MrJingleLifecycleTest.java
omniNotes/src/main/java/it/feio/android/omninotes/ListFragment.java

Fix for Mr. Jingel, it was not displayed after swiping note from archive to trash

Fix for Mr. Jingel, it was not displayed after swiping

---

omniNotes/src/main/java/it/feio/android/omninotes/CategoryActivity.java

reset windos size showing save button

Set CategoryActivity window size to 0.6 times the screen size

---

omniNotes/src/main/AndroidManifest.xml

Solves issue #888. Data loss due to screen rotation will not happen now.

Solves Issue #888

---

README.md

Adding equivalent windows command to build instructions.
